///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SomaGestao
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The DeleteBrowCampoObrigatorio recording.
    /// </summary>
    [TestModule("4edb761e-bd50-45c4-bb3b-59ca77dc1af1", ModuleType.Recording, 1)]
    public partial class DeleteBrowCampoObrigatorio : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SomaGestaoRepository repository.
        /// </summary>
        public static SomaGestaoRepository repo = SomaGestaoRepository.Instance;

        static DeleteBrowCampoObrigatorio instance = new DeleteBrowCampoObrigatorio();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public DeleteBrowCampoObrigatorio()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static DeleteBrowCampoObrigatorio Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmPrincipal.Form6528022'.", repo.FrmPrincipal.Form6528022Info, new RecordItemIndex(0));
            Validate.Exists(repo.FrmPrincipal.Form6528022Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 509;262.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(1));
            repo.BASEDETESTESBIANCHINI.Image1.Click("509;262");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 544;502.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(2));
            repo.BASEDETESTESBIANCHINI.Image1.Click("544;502");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Assistente'.", repo.Assistente.SelfInfo, new RecordItemIndex(3));
            Validate.Exists(repo.Assistente.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Assistente.ButtonSim' at 31;13.", repo.Assistente.ButtonSimInfo, new RecordItemIndex(4));
            repo.Assistente.ButtonSim.Click("31;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Assistente'.", repo.Assistente.SelfInfo, new RecordItemIndex(5));
            Validate.Exists(repo.Assistente.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Assistente.ButtonOK' at 36;3.", repo.Assistente.ButtonOKInfo, new RecordItemIndex(6));
            repo.Assistente.ButtonOK.Click("36;3");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'BASEDETESTESBIANCHINI.Image1' at 529;257.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(7));
            repo.BASEDETESTESBIANCHINI.Image1.DoubleClick("529;257");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 426;239.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(8));
            repo.BASEDETESTESBIANCHINI.Image1.Click("426;239");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Assistente'.", repo.Assistente.SelfInfo, new RecordItemIndex(9));
            Validate.Exists(repo.Assistente.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Assistente.ButtonSim' at 38;19.", repo.Assistente.ButtonSimInfo, new RecordItemIndex(10));
            repo.Assistente.ButtonSim.Click("38;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 1010;69.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(11));
            repo.BASEDETESTESBIANCHINI.Image1.Click("1010;69");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 538;494.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(12));
            repo.BASEDETESTESBIANCHINI.Image1.Click("538;494");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Assistente.ButtonSim' at 30;13.", repo.Assistente.ButtonSimInfo, new RecordItemIndex(13));
            repo.Assistente.ButtonSim.Click("30;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 1014;92.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(14));
            repo.BASEDETESTESBIANCHINI.Image1.Click("1014;92");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
