///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SomaGestao
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertBrowEndereco recording.
    /// </summary>
    [TestModule("3ab0147d-4d54-430c-91e2-6c16113d6da2", ModuleType.Recording, 1)]
    public partial class InsertBrowEndereco : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SomaGestaoRepository repository.
        /// </summary>
        public static SomaGestaoRepository repo = SomaGestaoRepository.Instance;

        static InsertBrowEndereco instance = new InsertBrowEndereco();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertBrowEndereco()
        {
            NomeCliente = "teste";
            Confirmacao = "{Return}";
            CEP = "13606321";
            NumEnd = "1";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertBrowEndereco Instance
        {
            get { return instance; }
        }

#region Variables

        string _NomeCliente;

        /// <summary>
        /// Gets or sets the value of variable NomeCliente.
        /// </summary>
        [TestVariable("03ca43d3-0ece-49f5-80e0-e0f35a5bcef1")]
        public string NomeCliente
        {
            get { return _NomeCliente; }
            set { _NomeCliente = value; }
        }

        string _Confirmacao;

        /// <summary>
        /// Gets or sets the value of variable Confirmacao.
        /// </summary>
        [TestVariable("a1f4dd64-5e0d-461c-91f8-784b92e0def1")]
        public string Confirmacao
        {
            get { return _Confirmacao; }
            set { _Confirmacao = value; }
        }

        string _CEP;

        /// <summary>
        /// Gets or sets the value of variable CEP.
        /// </summary>
        [TestVariable("983b57ed-8f28-4cbe-8476-ce033b94716a")]
        public string CEP
        {
            get { return _CEP; }
            set { _CEP = value; }
        }

        string _NumEnd;

        /// <summary>
        /// Gets or sets the value of variable NumEnd.
        /// </summary>
        [TestVariable("19d4028a-95f3-4b73-ba39-9df7845778ee")]
        public string NumEnd
        {
            get { return _NumEnd; }
            set { _NumEnd = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmPrincipal.Form65280'.", repo.FrmPrincipal.Form65280Info, new RecordItemIndex(0));
            Validate.Exists(repo.FrmPrincipal.Form65280Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 416;552.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(1));
            repo.BASEDETESTESBIANCHINI.Image1.Click("416;552");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NomeCliente' with focus on 'ProcuraFrmProcura'.", repo.ProcuraFrmProcura.SelfInfo, new RecordItemIndex(2));
            repo.ProcuraFrmProcura.Self.EnsureVisible();
            Keyboard.Press(NomeCliente);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'ProcuraFrmProcura'.", repo.ProcuraFrmProcura.SelfInfo, new RecordItemIndex(3));
            repo.ProcuraFrmProcura.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'ProcuraFrmProcura.TESTECNPJTESTE' at 95;13.", repo.ProcuraFrmProcura.TESTECNPJTESTEInfo, new RecordItemIndex(4));
            repo.ProcuraFrmProcura.TESTECNPJTESTE.DoubleClick("95;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(5));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad3}{NumPad6}{NumPad0}{NumPad6}{NumPad3}{NumPad2}{NumPad1}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(6));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad1}{NumPad3}{NumPad6}{NumPad0}{NumPad6}{NumPad3}{NumPad2}{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(7));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NumEnd' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(8));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(NumEnd);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(9));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 743;403.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(10));
            repo.BASEDETESTESBIANCHINI.Image1.Click("743;403");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'None' at 64;78.", repo.None.SelfInfo, new RecordItemIndex(11));
            repo.None.Self.Click("64;78");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 444;491.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(12));
            repo.BASEDETESTESBIANCHINI.Image1.Click("444;491");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 946;148.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(13));
            repo.BASEDETESTESBIANCHINI.Image1.Click("946;148");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
