///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace SomaGestao
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The InsertFrmConfiguracao_Semaforo recording.
    /// </summary>
    [TestModule("7cf3934b-bf87-4e46-be8e-5bddd86f9fec", ModuleType.Recording, 1)]
    public partial class InsertFrmConfiguracao_Semaforo : ITestModule
    {
        /// <summary>
        /// Holds an instance of the SomaGestaoRepository repository.
        /// </summary>
        public static SomaGestaoRepository repo = SomaGestaoRepository.Instance;

        static InsertFrmConfiguracao_Semaforo instance = new InsertFrmConfiguracao_Semaforo();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public InsertFrmConfiguracao_Semaforo()
        {
            CalculoMargem = "verde";
            Confirmacao = "{Return}";
            CorOcorrencia = "verde";
            NomeEmpresa = "matriz";
            PercentualVerde1 = "20";
            PercentualAmarelo1 = "50";
            PercentualVerde2 = "70";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static InsertFrmConfiguracao_Semaforo Instance
        {
            get { return instance; }
        }

#region Variables

        string _CalculoMargem;

        /// <summary>
        /// Gets or sets the value of variable CalculoMargem.
        /// </summary>
        [TestVariable("287a1ef4-f081-40b5-afc8-98f55f17135b")]
        public string CalculoMargem
        {
            get { return _CalculoMargem; }
            set { _CalculoMargem = value; }
        }

        string _Confirmacao;

        /// <summary>
        /// Gets or sets the value of variable Confirmacao.
        /// </summary>
        [TestVariable("96099e04-8e6b-4518-97d8-7049fe340ba4")]
        public string Confirmacao
        {
            get { return _Confirmacao; }
            set { _Confirmacao = value; }
        }

        string _CorOcorrencia;

        /// <summary>
        /// Gets or sets the value of variable CorOcorrencia.
        /// </summary>
        [TestVariable("dde1abf7-dc4e-4624-b377-0250a07bff6c")]
        public string CorOcorrencia
        {
            get { return _CorOcorrencia; }
            set { _CorOcorrencia = value; }
        }

        string _NomeEmpresa;

        /// <summary>
        /// Gets or sets the value of variable NomeEmpresa.
        /// </summary>
        [TestVariable("a126a6cb-95aa-4f04-ad3b-a786fe57daba")]
        public string NomeEmpresa
        {
            get { return _NomeEmpresa; }
            set { _NomeEmpresa = value; }
        }

        string _PercentualVerde1;

        /// <summary>
        /// Gets or sets the value of variable PercentualVerde1.
        /// </summary>
        [TestVariable("dcbf89cc-4079-4bb4-a6da-4908684d9c4d")]
        public string PercentualVerde1
        {
            get { return _PercentualVerde1; }
            set { _PercentualVerde1 = value; }
        }

        string _PercentualAmarelo1;

        /// <summary>
        /// Gets or sets the value of variable PercentualAmarelo1.
        /// </summary>
        [TestVariable("139e8eea-9d09-45ab-8598-8d622481965a")]
        public string PercentualAmarelo1
        {
            get { return _PercentualAmarelo1; }
            set { _PercentualAmarelo1 = value; }
        }

        string _PercentualVerde2;

        /// <summary>
        /// Gets or sets the value of variable PercentualVerde2.
        /// </summary>
        [TestVariable("8960e158-38e3-49a2-8c04-324b691889e7")]
        public string PercentualVerde2
        {
            get { return _PercentualVerde2; }
            set { _PercentualVerde2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmPrincipal.Form6528021'.", repo.FrmPrincipal.Form6528021Info, new RecordItemIndex(0));
            Validate.Exists(repo.FrmPrincipal.Form6528021Info);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 339;152.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(1));
            repo.BASEDETESTESBIANCHINI.Image1.Click("339;152");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CalculoMargem' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(2));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(CalculoMargem);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(3));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$CorOcorrencia' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(4));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(CorOcorrencia);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(5));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$NomeEmpresa' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(6));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(NomeEmpresa);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$Confirmacao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(7));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(Confirmacao);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'BASEDETESTESBIANCHINI.Image1' at 551;215.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(8));
            repo.BASEDETESTESBIANCHINI.Image1.MoveTo("551;215");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'BASEDETESTESBIANCHINI.Image1' at 664;213.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(9));
            repo.BASEDETESTESBIANCHINI.Image1.MoveTo("664;213");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PercentualVerde1' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(10));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(PercentualVerde1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'BASEDETESTESBIANCHINI.Image1' at 833;213.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(11));
            repo.BASEDETESTESBIANCHINI.Image1.MoveTo("833;213");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'BASEDETESTESBIANCHINI.Image1' at 833;213.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(12));
            repo.BASEDETESTESBIANCHINI.Image1.MoveTo("833;213");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PercentualAmarelo1' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(13));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(PercentualAmarelo1);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 445;149.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(14));
            repo.BASEDETESTESBIANCHINI.Image1.Click("445;149");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'Assistente'.", repo.Assistente.SelfInfo, new RecordItemIndex(15));
            Validate.Exists(repo.Assistente.SelfInfo);
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Assistente.ButtonOK' at 30;10.", repo.Assistente.ButtonOKInfo, new RecordItemIndex(16));
            repo.Assistente.ButtonOK.Click("30;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$PercentualVerde2' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(17));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(PercentualVerde2);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BASEDETESTESBIANCHINI.Image1' at 447;154.", repo.BASEDETESTESBIANCHINI.Image1Info, new RecordItemIndex(18));
            repo.BASEDETESTESBIANCHINI.Image1.Click("447;154");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating Exists on item 'FrmPrincipal.Form6528021'.", repo.FrmPrincipal.Form6528021Info, new RecordItemIndex(19));
            Validate.Exists(repo.FrmPrincipal.Form6528021Info);
            Delay.Milliseconds(100);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
